"""Init migrations

Revision ID: 61e5d79ecc8d
Revises: 
Create Date: 2021-07-15 20:19:40.552261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e5d79ecc8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=True),
    sa.Column('customer_field_rep_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.Text(), nullable=True),
    sa.Column('service_company_name', sa.Text(), nullable=True),
    sa.Column('wireline_company', sa.Text(), nullable=True),
    sa.Column('other_comments', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_field_rep',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('customer_field_rep_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trailer_id', sa.Integer(), nullable=True),
    sa.Column('powerpack_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('accumulator_id', sa.Integer(), nullable=True),
    sa.Column('hydrophones_id', sa.Integer(), nullable=True),
    sa.Column('hotspot_id', sa.Integer(), nullable=True),
    sa.Column('computer_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formation',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pad',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pad_uuid', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('pad_name', sa.Text(), nullable=False),
    sa.Column('number_of_wells', sa.Integer(), nullable=True),
    sa.Column('well_spacing', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_uuid', sa.String(length=36), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('well',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_uuid', sa.String(length=36), nullable=False),
    sa.Column('pad_id', sa.Integer(), nullable=False),
    sa.Column('well_name', sa.Text(), nullable=True),
    sa.Column('well_api', sa.Text(), nullable=True),
    sa.Column('formation_id', sa.Integer(), nullable=True),
    sa.Column('num_stages', sa.Integer(), nullable=True),
    sa.Column('total_planned_stage', sa.Integer(), nullable=True),
    sa.Column('total_perfs', sa.Integer(), nullable=True),
    sa.Column('total_clusters', sa.Integer(), nullable=True),
    sa.Column('frac_system', sa.Text(), nullable=True),
    sa.Column('fluid_system', sa.Text(), nullable=True),
    sa.Column('well_start_time', sa.DateTime(), nullable=True),
    sa.Column('well_end_time', sa.DateTime(), nullable=True),
    sa.Column('bottom_hole_latitude', sa.Float(), nullable=True),
    sa.Column('bottom_hole_longitude', sa.Float(), nullable=True),
    sa.Column('surface_longitude', sa.Float(), nullable=True),
    sa.Column('surface_latitude', sa.Float(), nullable=True),
    sa.Column('lateral_length', sa.Float(), nullable=True),
    sa.Column('lateral_length_unit', sa.Text(), nullable=True),
    sa.Column('measured_depth', sa.Float(), nullable=True),
    sa.Column('vertical_depth', sa.Float(), nullable=True),
    sa.Column('vertical_depth_unit', sa.Text(), nullable=True),
    sa.Column('estimated_surface_vol', sa.Float(), nullable=True),
    sa.Column('estimated_bbls', sa.Float(), nullable=True),
    sa.Column('estimated_gallons', sa.Float(), nullable=True),
    sa.Column('liner1_od', sa.Float(), nullable=True),
    sa.Column('liner1_wt', sa.Float(), nullable=True),
    sa.Column('liner1_id', sa.Text(), nullable=True),
    sa.Column('liner1_depth_md', sa.Float(), nullable=True),
    sa.Column('liner2_od', sa.Float(), nullable=True),
    sa.Column('liner2_wt', sa.Float(), nullable=True),
    sa.Column('liner2_id', sa.Text(), nullable=True),
    sa.Column('liner2_depth_md', sa.Float(), nullable=True),
    sa.Column('measured_depth_unit', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('well')
    op.drop_table('project')
    op.drop_table('pad')
    op.drop_table('formation')
    op.drop_table('equipment')
    op.drop_table('customer_field_rep')
    op.drop_table('client')
    # ### end Alembic commands ###
